import { format } from "@formkit/tempo"

// 👇 Try changing this to "fr"
const l = "en"
const t = new Date()

format(t, "YYYY-MM-DD", l)
format(t, "MMM D, YYYY", l)
format(t, "MMMM D, YYYY", l)
format(t, "DD/MM/YYYY", l)
format(t, "hh:mm:ss", l)
format(t, "h:mm:ss a", l)
format(t, "MMMM D, YYYY h:mm a", l)
format(t, "dddd, MMMM D, YYYY", l)
format(t, "M/D/YY", l)
format(t, "h:mm:ss A", l)
format(t, "YYYY-MM-DD HH:mm:ss", l)
format(t, "MMM D, YYYY HH:mm", l)
format(t, "dddd, MMMM D, YYYY h:mm:ss a", l)
format(t, "h:mm A", l)
format(t, "YYYY-MM-DDTHH:mm:ssZ", l)
format(t, "YY-M-D", l)
format(t, "YYYY/MM/DD", l)
format(t, "MMM D, YYYY HH:mm:ss", l)
format(t, "D MMMM YYYY", l)
format(t, "HH:mm", l)
format(t, "h:mm a Z", l)
format(t, "dddd, MMMM D, YYYY h:mm A", l)
format(t, "M/D/YYYY", l)
format(t, "hh:mm:ss a Z", l)
format(t, "YYYY-MM-DDTHH:mm:ss", l)
format(t, "MMM D, YYYY h:mm A", l)
format(t, "dddd, MMMM D, YYYY HH:mm:ss", l)
format(t, "h:mm:ss A Z", l)
format(t, "YY/MM/DD", l)
format(t, "YYYY MMMM D", l)
format(t, "M-D-YY", l)
format(t, "HH:mm:ss.SSS", l)
format(t, "YYYY-MM-DDTHH:mm:ss.SSSZ", l)
