name: Vitest
on: [push, workflow_dispatch]
jobs:
  vitest-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - run: pnpm install
      - run: pnpm test
